/**
 * Provision a doorbell. The only place a device credential is ever made.
 *
 * Three shapes, because the job has three shapes:
 *
 *   one Pi, by hand      a block of text to read while holding the board
 *   one Pi, scripted     --json, a birth certificate on stdout
 *   fifty Pis, a line    --batch 50, one file and one label row per unit
 *
 * THE BIRTH CERTIFICATE IS A CONTRACT. `pi/porchlight-firstboot.py` reads
 * it from /boot/firmware/porchlight.json at first boot, installs the
 * credential, patches the config, sets the hostname and destroys the
 * file. The field names below are parsed by that script, so renaming one
 * here breaks every unit flashed afterwards:
 *
 *   {
 *     "deviceId":      "porch-1",
 *     "credential":    "pl_porch-1_...",
 *     "url":           "https://porchlight.example",
 *     "name":          "Front Door",
 *     "claimCode":     "7K2M9P",
 *     "setupSsid":     "Porchlight-3WK7",
 *     "setupPassword": "eight characters or more"
 *   }
 *
 * deviceId, credential and url are required - without them the device
 * refuses the card and lights the fault pattern rather than
 * half-provisioning itself. The rest are optional and the device degrades
 * sensibly without them.
 *
 * The production line is then: flash N cards from one image, copy one
 * JSON onto each boot partition, stick on the matching label. Two seconds
 * a unit, no per-unit image, no re-flash.
 *
 *   node scripts/mint-device.mjs --device-id porch-1 --name "Front Door"
 *   node scripts/mint-device.mjs --device-id porch-1 --json > porchlight.json
 *   node scripts/mint-device.mjs --batch 50 --prefix porch --out ./cards
 *   node scripts/mint-device.mjs --device-id porch-1 --force
 *   node scripts/mint-device.mjs --device-id porch-1 --attach <mongo id>
 *   node scripts/mint-device.mjs --device-id porch-1 --force --reclaim
 *
 * --force re-mints an existing device: the new credential replaces the
 * old one, which stops working immediately. That is the recovery path for
 * a lost credential and the revocation path for a Pi that walked off.
 * There is no rotate-over-the-network endpoint by design, so this means
 * re-flashing the card.
 *
 * --attach binds hardware to a doorbell that already exists in the app
 * (one a user created by tapping "add doorbell"), rather than making a
 * new record. Its members are left alone.
 *
 * --reclaim is the support tool for a doorbell that changed hands: it
 * clears the spent claim and issues a new code. It refuses while an owner
 * membership still exists, because that owner is presumably still using
 * the doorbell - releasing it is their action, not support's.
 *
 * WHAT IS NO LONGER PRINTED HERE: the share code. It used to be, beside
 * the credential, and the first person to type it became the owner. On a
 * doorbell bolted to the outside of a house, with the code on a sticker
 * on the case, that made a photograph of the unit enough to take
 * ownership of a camera pointed at someone's front door. Ownership now
 * comes from the claim code below, which is single-use; share codes are
 * generated by an owner inside the app and are printed on nothing. See
 * src/utils/claimCode.js.
 */
import 'dotenv/config';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import mongoose from 'mongoose';
import { Device } from '../src/models/Device.js';
import { Membership } from '../src/models/Membership.js';
// Imported for its side effect: registering the schema. Reporting the
// current owner populates Membership.user, and Mongoose can only resolve
// ref: 'User' if the model has been registered on this connection. In the
// server that happens via the route graph; a standalone script has no
// route graph, so it has to say so itself.
import '../src/models/User.js';
import {
  generateDeviceCredential,
  isValidDeviceId,
  normalizeDeviceId
} from '../src/utils/deviceCredential.js';
import { claimCodeConfigured, generateClaimCode, hashClaimCode } from '../src/utils/claimCode.js';
import { generateSetupAp } from '../src/utils/setupAp.js';

function arg(flag) {
  const i = process.argv.indexOf(flag);
  return i === -1 ? null : process.argv[i + 1] ?? null;
}
const has = (flag) => process.argv.includes(flag);

const deviceId = normalizeDeviceId(arg('--device-id'));
const name = arg('--name');
const location = arg('--location');
const attachTo = arg('--attach');
const force = has('--force');
const reclaim = has('--reclaim');

const jsonMode = has('--json');
const batchSize = arg('--batch') === null ? 0 : Number(arg('--batch'));
const prefix = normalizeDeviceId(arg('--prefix'));
const startAt = arg('--start') === null ? null : Number(arg('--start'));
const outDir = arg('--out') || './cards';
const serverUrl = arg('--url') || process.env.PUBLIC_API_URL || '';

// --json promises one object on stdout and nothing else, so every word of
// progress goes to stderr in that mode. Redirecting stdout to a file then
// gives a parseable certificate rather than a certificate with retry
// chatter in front of it.
const log = (...args) => (jsonMode ? console.error(...args) : console.log(...args));

/**
 * Retries every database call, not just the connect.
 *
 * This cluster's TLS handshake fails often enough that a single failure
 * mid-run is routine, and it clears the whole connection pool - so an
 * operation after a successful connect fails just as easily as the
 * connect did. For a tool someone runs while holding a Raspberry Pi,
 * "run it again" is a bad answer. For a tool minting fifty of them it is
 * a worse one.
 */
async function retry(what, run, attempts = 6) {
  let last;
  for (let i = 1; i <= attempts; i++) {
    try {
      return await run();
    } catch (err) {
      last = err;
      if (i < attempts) {
        log(`  ${what} attempt ${i}/${attempts} failed: ${err.message.split('\n')[0].slice(0, 70)}`);
        await new Promise((r) => setTimeout(r, 1200));
      }
    }
  }
  throw last;
}

async function connectWithRetry() {
  // Small pool for the same reason the server uses one: fewer concurrent
  // handshakes means fewer chances to trip the failure above.
  await retry('connect', () =>
    mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 15000, maxPoolSize: 5 })
  );
}

/**
 * Saving is retried too, which is only safe because Mongoose generates
 * the _id client-side: a retry writes the same document to the same id.
 * If an earlier attempt actually landed and we retried anyway, the insert
 * collides on _id - which means it worked, not that it failed.
 */
async function saveWithRetry(device) {
  await retry('save', async () => {
    try {
      await device.save();
    } catch (err) {
      if (err.code === 11000 && err.keyPattern?._id) return;
      throw err;
    }
  });
}

function usage(message) {
  console.error(`\n${message}\n`);
  console.error('  one unit    node scripts/mint-device.mjs --device-id <slug> [--name "Front Door"]');
  console.error('                               [--location "..."] [--force] [--reclaim]');
  console.error('                               [--attach <mongo id>] [--json]');
  console.error('  a batch     node scripts/mint-device.mjs --batch <n> --prefix <slug>');
  console.error('                               [--start <n>] [--out ./cards]');
  console.error('  server url  --url https://porchlight.example, or PUBLIC_API_URL\n');
  process.exit(1);
}

/**
 * Everything a device is born knowing, assembled in one place so the
 * single and batch paths cannot drift apart on field names.
 *
 * The setup SSID and password are deliberately NOT stored on the Device.
 * They are only meaningful before the unit has joined a network, they are
 * only useful to somebody standing within radio range of it, and the
 * recovery path for a lost label is a re-mint and a re-flash - which
 * issues new ones anyway. A database that does not hold them cannot leak
 * them.
 */
function birthCertificate({ device, credential, claimCode, setupAp }) {
  const certificate = {
    deviceId: device.deviceId,
    credential,
    url: serverUrl,
    name: device.name,
    ...setupAp
  };
  // Omitted rather than null for a doorbell that is already claimed: the
  // field is optional on the device side, and a certificate carrying no
  // claim code says "this one has an owner already" without the device
  // needing to understand why.
  if (claimCode) certificate.claimCode = claimCode;
  return certificate;
}

/**
 * Mints one unit: credential, claim code, and the record to match.
 *
 * Resolves which record the hardware belongs to *before* minting
 * anything - a credential printed for a device that then fails to save is
 * a secret loose in a terminal for no reason.
 */
async function mintOne({ id, recordId, wantName, wantLocation }) {
  let device;
  if (recordId) {
    if (!mongoose.isValidObjectId(recordId)) usage(`--attach needs a device id; "${recordId}" is not one.`);
    device = await retry('lookup', () => Device.findById(recordId));
    if (!device) usage(`No doorbell with id ${recordId}.`);
    if (device.credentialHash && !force) {
      usage(`${device.name} already has hardware provisioned. Re-run with --force to replace it.`);
    }
  } else {
    const existing = await retry('lookup', () => Device.findOne({ deviceId: id }));
    if (existing && !force) {
      usage(`"${id}" is already provisioned. Re-run with --force to replace its credential.`);
    }
    device = existing || new Device();
  }

  if (reclaim) {
    const owner = await retry('owner lookup', () =>
      Membership.findOne({ device: device._id, role: 'owner' })
    );
    if (owner) {
      usage(
        `${device.name} still has an owner. Releasing a doorbell is the owner's action - have ` +
          'them delete it in the app, or remove the owner membership first.'
      );
    }
    device.claimedAt = null;
  }

  const { credential, credentialHash } = generateDeviceCredential(id);
  const replacing = Boolean(device.credentialHash);

  device.deviceId = id;
  device.credentialHash = credentialHash;
  device.provisionedAt = new Date();
  if (wantName) device.name = wantName;
  if (wantLocation) device.location = wantLocation;

  // A doorbell that is already claimed gets no new claim code. Issuing
  // one would be a second live path to ownership of a doorbell somebody
  // already owns, which is the whole thing A6 exists to prevent.
  let claimCode = null;
  if (!device.claimedAt) {
    // Random, so a collision is conceivable. The unique index is the real
    // guarantee; this loop turns a duplicate key into a retry.
    for (let attempt = 0; attempt < 5; attempt++) {
      claimCode = generateClaimCode();
      device.claimCodeHash = hashClaimCode(claimCode);
      try {
        await saveWithRetry(device);
        break;
      } catch (err) {
        if (err.code === 11000 && err.keyPattern?.claimCodeHash) continue;
        throw failSave(err, id);
      }
    }
  } else {
    try {
      await saveWithRetry(device);
    } catch (err) {
      throw failSave(err, id);
    }
  }

  // Drawn once per unit and carried, rather than generated by whoever
  // renders it: printing one SSID and writing a different one into the
  // certificate is a unit whose sticker does not match the doorbell.
  return { device, credential, claimCode, replacing, setupAp: generateSetupAp() };
}

function failSave(err, id) {
  if (err.code === 11000 && err.keyPattern?.deviceId) {
    usage(`Another doorbell is already provisioned as "${id}".`);
  }
  return err;
}

/** Quoted only when it has to be, so the file stays readable. */
function csvCell(value) {
  const s = String(value ?? '');
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/**
 * The next free slot in a numbered series.
 *
 * A production run is one batch after another, and asking the operator to
 * remember where the last one stopped is asking for two units minted as
 * porch-0050.
 */
// Zero-padded to four, so the ids sort the way the boxes are stacked.
function seriesId(seriesPrefix, n) {
  return `${seriesPrefix}-${String(n).padStart(4, '0')}`;
}

async function nextIndex(seriesPrefix) {
  const rows = await retry('series lookup', () =>
    Device.find({ deviceId: new RegExp(`^${seriesPrefix}-\\d+$`) }, { deviceId: 1 }).lean()
  );
  const highest = rows.reduce((max, r) => {
    const n = Number(String(r.deviceId).slice(seriesPrefix.length + 1));
    return Number.isFinite(n) && n > max ? n : max;
  }, 0);
  return highest + 1;
}

async function runBatch() {
  // Validated as a device id, not just as non-empty: it is interpolated
  // into a RegExp below, and the id pattern already excludes every
  // character that would mean something there.
  if (!prefix || !isValidDeviceId(prefix)) {
    usage('--batch needs --prefix as a slug, e.g. --prefix porch');
  }
  if (!Number.isInteger(batchSize) || batchSize < 1 || batchSize > 1000) {
    usage('--batch takes a whole number of units, 1 to 1000.');
  }
  if (force || attachTo || reclaim) {
    usage('--batch mints new units only: --force, --attach and --reclaim are one at a time.');
  }

  const first = startAt !== null ? startAt : await nextIndex(prefix);
  if (!Number.isInteger(first) || first < 1) usage('--start takes a whole number from 1.');

  const ids = Array.from({ length: batchSize }, (_, i) => seriesId(prefix, first + i));

  /*
   * Everything that can refuse this batch is checked before a single unit
   * is minted, and that is the whole reason this block exists rather than
   * letting mintOne say no on the way past.
   *
   * A batch that dies on unit thirty has already written twenty-nine
   * credentials and spent twenty-nine claim codes. Those units are real
   * rows in the database with secrets that exist in one place - the files
   * just written - so an operator who deletes the half-finished output
   * directory and starts again has quietly created twenty-nine doorbells
   * nobody can ever provision. Refusing up front costs one query.
   */
  const tooLong = ids.find((id) => !isValidDeviceId(id));
  if (tooLong) usage(`"${tooLong}" is not a valid device id - shorten the prefix.`);

  const taken = await retry('collision check', () =>
    Device.find({ deviceId: { $in: ids } }, { deviceId: 1 }).lean()
  );
  if (taken.length > 0) {
    const names = taken.map((d) => d.deviceId).join(', ');
    usage(
      `Already provisioned: ${names}. Re-mint those one at a time with --force, or move the ` +
        `batch past them with --start ${(await nextIndex(prefix))}.`
    );
  }

  mkdirSync(outDir, { recursive: true });

  const rows = [];
  log(`\n  Minting ${batchSize} units, ${ids[0]} to ${ids[ids.length - 1]}\n`);

  for (const id of ids) {
    const minted = await mintOne({ id, wantName: name, wantLocation: location });
    const certificate = birthCertificate(minted);

    // One directory per unit, so copying is `cp cards/<id>/porchlight.json
    // <boot partition>/` with no rename step. A rename step on a
    // production line is a step somebody skips.
    const dir = join(outDir, id);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'porchlight.json'), `${JSON.stringify(certificate, null, 2)}\n`, {
      encoding: 'utf8',
      // 0600: the file holds a credential and a code that grants
      // ownership. Default umask would leave a batch of fifty of them
      // world-readable on the build machine.
      mode: 0o600
    });

    rows.push({
      deviceId: id,
      name: certificate.name,
      claimCode: certificate.claimCode,
      setupSsid: certificate.setupSsid,
      setupPassword: certificate.setupPassword,
      record: String(minted.device._id)
    });

    log(`  ${id}  claim ${certificate.claimCode}  ap ${certificate.setupSsid}`);
  }

  // What the label printer reads. `qr` is the payload to encode, not an
  // image - rendering one would mean a new dependency, and every label
  // program already does it from a column.
  const csv = [
    ['deviceId', 'name', 'claimCode', 'setupSsid', 'setupPassword', 'qr', 'record'].join(','),
    ...rows.map((r) =>
      [r.deviceId, r.name, r.claimCode, r.setupSsid, r.setupPassword, r.claimCode, r.record]
        .map(csvCell)
        .join(',')
    )
  ].join('\n');

  const labels = join(outDir, 'labels.csv');
  writeFileSync(labels, `${csv}\n`, { encoding: 'utf8', mode: 0o600 });

  log('');
  log(`  ${batchSize} certificates written to ${outDir}/<device-id>/porchlight.json`);
  log(`  labels               ${labels}`);
  log('');
  log('  ---- shown once, not recoverable ------------------------------');
  log('  Those files hold every credential and claim code in this batch.');
  log('  Nothing can reprint them: a lost certificate means --force and a');
  log('  re-flash. Move them to the line, then delete them.');
  log('  ---------------------------------------------------------------');
  log('');
}

async function runSingle() {
  if (!deviceId) usage('--device-id is required.');
  if (!isValidDeviceId(deviceId)) {
    usage(`"${deviceId}" is not a valid device id: 2-32 chars, lowercase letters, digits and hyphens.`);
  }

  const minted = await mintOne({
    id: deviceId,
    recordId: attachTo,
    wantName: name,
    wantLocation: location
  });
  const { device, credential, claimCode, replacing } = minted;

  if (jsonMode) {
    // One object and nothing else.
    process.stdout.write(`${JSON.stringify(birthCertificate(minted), null, 2)}\n`);
    return;
  }

  const owner = await retry('owner lookup', () =>
    Membership.findOne({ device: device._id, role: 'owner' }).populate('user', 'email')
  );

  log('');
  log(replacing ? '  RE-MINTED - the previous credential no longer works' : '  Provisioned');
  log('');
  log(`  doorbell     ${device.name}${device.location ? ` (${device.location})` : ''}`);
  log(`  device id    ${device.deviceId}`);
  log(`  record       ${device._id}`);
  log('');
  log('  ---- shown once, not recoverable ------------------------------');
  log('');
  log(`  credential   ${credential}`);
  log('               write to the Pi, readable only by the daemon');
  log('');

  if (claimCode) {
    log(`  claim code   ${claimCode}`);
    log('               on the sticker. Whoever enters this first becomes');
    log('               the owner, once - it is consumed by that claim.');
    log('');
    log(`  setup wi-fi  ${minted.setupAp.setupSsid} / ${minted.setupAp.setupPassword}`);
    log('               the access point shown before it has a network');
    log('');
  } else if (owner) {
    log(`  owner        ${owner.user?.email || owner.user} (claimed already)`);
    log('               no new claim code: it has an owner. They can share');
    log('               it from inside the app, or --reclaim to release it.');
    log('');
  }

  log('  ---------------------------------------------------------------');
  log('');
  log('  Write these into /boot/firmware/porchlight.json, or re-run with');
  log('  --json to have that file generated for you.');
  log('');
}

async function main() {
  if (!process.env.MONGODB_URI) throw new Error('MONGODB_URI is not set');

  // Checked before anything is minted rather than at the first hash: a
  // batch that dies on unit thirty has already written twenty-nine cards.
  if (!claimCodeConfigured) {
    throw new Error(
      'CLAIM_CODE_PEPPER is not set (needs 16+ characters). Claim codes are hashed under it, ' +
        'so codes minted without it could never be claimed. Generate one with:\n' +
        '  node -e "console.log(require(\'crypto\').randomBytes(32).toString(\'hex\'))"'
    );
  }

  if (!serverUrl) {
    throw new Error(
      'No server url. The device needs one to reach this API and refuses its card without it. ' +
        'Pass --url https://porchlight.example, or set PUBLIC_API_URL.'
    );
  }

  await connectWithRetry();

  if (batchSize) await runBatch();
  else await runSingle();

  await mongoose.disconnect();
}

main().catch(async (err) => {
  console.error('\nFailed:', err.message);
  await mongoose.disconnect().catch(() => {});
  process.exit(1);
});
